### ISSUE TITLE
seq.calculateKspacePP() error on certain non-cartesian trajectories

### ISSUE THREAD

**Issue by pkash16** [imr-framework/pypulseq#117]
**Describe the bug**
I am working on a non-cartesian trajectory-based pulse sequence design which seems to have some issues with seq.calculateKSpacePP(). The sequence passes timing checks but errors with calculateKSpacePP, somewhere in a  ported version of the MATLAB of a piecewise polynomial function.

The following error message shows up:

>   File "run_hawk_to_pulseq_convertor.py", line 19, in <module>
    k_traj_adc, k_traj, t_excitation, t_refocusing, t_adc = seq.calculate_kspacePP()
  File "/[...]/sequence.py", line 528, in calculate_kspacePP
    k_traj[i, it] = self.ppval_MATLAB(gm_pp[i], t_ktraj[it])
  File "[...]/sequence.py", line 1152, in ppval_MATLAB
    corresponding_pp = np.nonzero((x < breaks))[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**To Reproduce**
- [Share the pulse sequence code, if possible.](https://github.com/usc-mrel/hawk_to_pypulseq)

**Desktop (please complete the following information):**
 - OS: macOS
- `pypulseq` version: latest dev branch.

**Comment by bilal-tasdelen** [comment]
@sravan953 I looked at the issue. It seems the problem comes from the `ppval_MATLAB` function. The following returns an empty array `np.nonzero((x < breaks))`, whenever x is bigger than any value in breaks, which I believe is the domain of the polynomial. I am not very familiar with the implementation, but my understanding of the issue is the function is not able to do extrapolation?

Do you think the input is problematic, and we should never have an x outside the domain, or the function should be fixed?

**Comment by pkash16** [comment]
I found the problem with this. It turns out when using arbitrary waveforms, I had accidentally chopped off the last zero on the gradient waveforms, making the kspace integrals be inaccurate. When fixing that issue, the trajectories look correct and there is no error with calculateKSpacePP().

I don't think this bug has anything to do with calculateKSpacePP(), but it may be worth showing a warning if gradient waveforms do not end with "zero" as I think the scanner is forcing them to be zero anyways.
